# Generated by Django 3.2.8 on 2022-01-08 12:35

from django.db import migrations, models
import django.db.models.deletion
import main.validators
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=tasks.models.create_task_document_directory_path, validators=[main.validators.validate_file_extension])),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tasks.task')),
            ],
            options={
                'db_table': 'task_document',
            },
        ),
    ]
