# Generated by Django 3.2.8 on 2022-01-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('ISSUED', 'Выдано'), ('STARTED', 'В процессе'), ('FINISHED', 'Выполнено'), ('CHECK', 'Проверка'), ('CLOSED', 'Завершено')], default='ISSUED', max_length=10),
        ),
    ]
