# Generated by Django 3.2.8 on 2022-02-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20220114_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdocument',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
