# Generated by Django 3.2.8 on 2022-02-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deal_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='step_id',
            field=models.UUIDField(null=True),
        ),
    ]
