# Generated by Django 3.2.8 on 2021-12-14 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211125_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetail',
            old_name='bank_account',
            new_name='ks',
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='bank_info',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='rs',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\d{20}$')]),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
