# Generated by Django 3.2.8 on 2022-02-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bankDetails_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='beneficiary_id',
            field=models.UUIDField(null=True),
        ),
    ]
