# Generated by Django 3.2.8 on 2022-02-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220211_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bankDetails_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='beneficiary_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_date',
            field=models.DateField(null=True),
        ),
    ]
