# Generated by Django 3.2.8 on 2022-02-15 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220211_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='okpo',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^(\\d{8}|\\d{10})$')]),
        ),
    ]
