# Generated by Django 3.2.8 on 2022-03-14 20:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_companyuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
