# Generated by Django 3.2.8 on 2022-03-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_company_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='receipt_data',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
