# Generated by Django 3.2.8 on 2022-03-13 19:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0009_user_is_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_period', models.DateField()),
                ('to_period', models.DateField()),
                ('active_workers', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='main.company')),
            ],
            options={
                'db_table': 'receipt',
            },
        ),
    ]
